### ISSUE TITLE
OSError: Model file not found: hubert/checkpoint_best_legacy_500.pt

### ISSUE THREAD

**Issue by panlina** [camenduru/so-vits-svc-colab#1]
I just opened [this colab](https://colab.research.google.com/github/camenduru/so-vits-svc-colab/blob/main/so_vits_svc_colab.ipynb) and ran it, uploaded my input audio to `raw` folder, and clicked "convert". I got this:

<img width="789" alt="image" src="https://github.com/camenduru/so-vits-svc-colab/assets/18240847/4af2d0a7-e37d-4053-903d-0472c149c9f3">

`OSError: Model file not found: hubert/checkpoint_best_legacy_500.pt`

Is this file supposed to be there after running previous commands?

**Comment by camenduru** [comment]
Hi @panlina 👋 thanks for the info ❤ please try again

**Comment by panlina** [comment]
It's fixed. Thanks!
